services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://redpanda:9092
    ports:
      - "9092:9092"
      - "9644:9644"
    volumes:
      - redpanda_data:/var/lib/redpanda/data

  console:
    image: docker.redpanda.com/redpandadata/console:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKERS: redpanda:9092
    depends_on:
      - redpanda

  producer:
    build: ./producer
    depends_on:
      - redpanda
    environment:
      - TOPIC=client-tickets
      - KAFKA_BOOTSTRAP=redpanda:9092

  spark-consumer:
    build: ./consumer
    depends_on:
      - redpanda
    volumes:
      - ./output:/data
    command: >
      sh -lc "mkdir -p /tmp/ivy /data/checkpoints /data/parquet &&
      /opt/spark/bin/spark-submit
      --conf spark.jars.ivy=/tmp/ivy
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1
      /opt/app/spark_consumer.py"
  
  spark-insight:
    build: ./consumer
    volumes:
      - ./output:/data
    profiles:
      - batch
    command: >
      /opt/spark/bin/spark-submit /opt/app/spark_insight.py

volumes:
  redpanda_data: